permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: TnT
description: "Just the Tip"
email: sam.wolfand@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: ""
repository: "https://github.com/swolfand/swolfand.github.io"
disqus_shortname: ""
google_analytics: 

# social footer
social:
  github:
    slug: github
    link: http://github.com/swolfand
  facebook:
    slug: facebook
    link:
  twitter:
    slug: twitter
    link: http://twitter.com/swolfand
  instagram:
    slug: instagram
    link: http://instagram.com/thewolf77
  linkedin:
    slug: linkedin
    link: http://linkedin.com/in/samwolfand
